### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by timotejvesel** [timotejvesel/APPR-2017-18#2]
Pozdravljeni,

projekt sem dokončal in ga pošiljam v pregled.

Lep pozdrav

**Comment by jaanos** [comment]
V redu, nimam pripomb. Dodal bom povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjal, mi prosim javi, da posodobim povezavo.
